### ISSUE TITLE
Nor-BTS survey years

### ISSUE THREAD

**Issue by AquaAuma** [AquaAuma/FishGlob_data#19]
@LaurenePecuchet advises to remove years prior to 2004 because data are not good enough for biodiversity studies?
Or maybe just mention in the usage notes of the paper? Using that data for other purposes could still be good

**Comment by jepa** [comment]
I suggest we put a note in the summary report. But we might want to discuss as a group what our overall decission is and apply it for all surveys

**Comment by AquaAuma** [comment]
@LaurenePecuchet added another issue about this elsewhere, so I'm closing this one as they relate to the same issue
