### ISSUE TITLE
Zeros for `area_swept` and infinities for `num_cpua`

### ISSUE THREAD

**Issue by edwardlavender** [AquaAuma/FishGlob_data#21]
There are 22 records for survey GSL-N with `area_swept = 0` (and `num_cpua = Inf`).

How can swept area be zero? Is this a bug (e.g., in matching swept areas onto catch records) or signature of invalid trawl(s) that is not included in current routines? (I am not familiar with the details of how GSL-N surveys are recorded.)

```
# Load data
load(url("https://github.com/AquaAuma/FishGlob_data/blob/main/outputs/Compiled_data/FishGlob_public_clean.RData?raw=true"))
# Identify area_swept = 0 records
data[which(data$area_swept == 0), c("survey", "haul_id", "area_swept", "accepted_name", "num", "num_cpue", "num_cpua")]
```

**Comment by AquaAuma** [comment]
missing swept area estimates even after model fits: 

<img width="908" alt="image" src="https://github.com/AquaAuma/FishGlob_data/assets/46930001/960feddb-b9dd-46fa-a4a2-d4a0dd37fdc6">

**Comment by AquaAuma** [comment]
@zoekitchel do you think you could check the GSL survey and probably replace 0 swept area values by NAs, or figure out why we have 0 values? Thanks

**Comment by mpinsky** [comment]
@jepa , this would be one of the North American fixes to implement. It would mean replacing the GSL-S and GSL-N (Gulf of St. Lawrence South and North) swept area=0 values with NA early enough in the data processing so that num_cpua also gets calculated as NA. Thank you!

**Comment by jepa** [comment]
Done, see my last push(es).  https://github.com/AquaAuma/FishGlob_data/commit/d688f21da7bb0adf794b65b9a0681bda4513f68c, da2d85ed2f4fd5858c6d2c807c83ec9d65478d4e and ebd7193c425600fa7b9c7932198d784abee32e07
