### ISSUE TITLE
missing aphid id

### ISSUE THREAD

**Issue by AquaAuma** [AquaAuma/FishGlob_data#23]
the last public version of the data has some missing aphia id codes from worms, probably a mistake that can be easily fixed with worms

**Comment by AquaAuma** [comment]
[missing_aphia_id.csv](https://github.com/AquaAuma/FishGlob_data/files/11464637/missing_aphia_id.csv)

**Comment by jepa** [comment]
Not sure why this happened but is fixed.  

- For Nor-BTS I had to do a quick fix, see commit 24a0c6ac6d997e2af592656bfe8ddae095b4bf1f
- For WCAN I did a manual fix, see commit dc7e074c232c790c1994b53359824e5fedaf4777
