### ISSUE TITLE
summary update of figures

### ISSUE THREAD

**Issue by AquaAuma** [AquaAuma/FishGlob_data#28]
make sure all axes years are visible and include most years @jepa (related to reviewer comment, see response to reviewers for references

**Comment by jepa** [comment]
I looked for the response to reviewers and couldn't find the reference.  Can you be more specific on what figures precisely or what is the comment in the document? Thanks :)

**Comment by jepa** [comment]
Comment for reference:
![image](https://github.com/AquaAuma/FishGlob_data/assets/16725517/967f58c8-387e-4d3c-95f3-797910bb5e7a)

**Comment by AquaAuma** [comment]
ha! good catch, I don't think I had understood this right: it's the integrated dataset figures in summary/fishglob_summary and code is summary/fishglob.R

I think I'm the one who had done it
![image](https://github.com/AquaAuma/FishGlob_data/assets/46930001/76e0c4cd-c2d9-463b-abea-e5fe137ba77a)
obviously this figures is not well plotted...

**Comment by AquaAuma** [comment]
🤓
