### ISSUE TITLE
Norwegian survey should not be used

### ISSUE THREAD

**Issue by LaurenePecuchet** [AquaAuma/FishGlob_data#29]
The Norwegian bottom trawl survey that has been used so far in FishGlob has many errors and should not be used in any analysis until it has been replaced by the correct dataset.

**Comment by AquaAuma** [comment]
@tomjwebb and @edwardlavender big warning here, we were recently notified by IMR about this, and we will replace the Norwegian survey dataset in the coming week(s)

**Comment by edwardlavender** [comment]
Thanks for the heads up!

**Comment by AquaAuma** [comment]
that might disappear with the new dataset because it's quite a different one

**Comment by AquaAuma** [comment]
@LaurenePecuchet are we all good with the code or are there things I need to double check besides loading the data?

**Comment by AquaAuma** [comment]
Dataset was replaced by the Barents Sea ecosystem survey available here for year 2021 http://metadata.nmdc.no/metadata-api/landingpage/3b4b5ee0f92a647642ffffdec39c8814 and see reports: 
- https://www.hi.no/en/hi/nettrapporter/imrpinro/2011/atlas_august_2011_press_quality_til_web
- https://www.hi.no/en/hi/nettrapporter/rapport-fra-havforskningen-en-2021-15
