### ISSUE TITLE
summary for Northern GSL

### ISSUE THREAD

**Issue by AquaAuma** [AquaAuma/FishGlob_data#36]
the summary is not working, and I cannot seem to find the issue because my R session aborts every time I try to investigate

**Comment by AquaAuma** [comment]
same for running the flagging functions in the R code

**Comment by AquaAuma** [comment]
![image](https://github.com/AquaAuma/FishGlob_data/assets/46930001/3b8aace5-ebe8-4eb3-81ad-17cb54d4b58d)
With ddgridR there is an issue in lat/long conversion in creating the grid that end up in the output figures, and probably the survey files (wrong grid cell codes?)

error @jepa Juliano is getting: 

```
######### Apply trimming per survey_unit method 1
#apply trimming for hex size 7
dat_new_method1_hex7 <- apply_trimming_per_survey_unit_method1(clean_GSLnor, 7)

FATAL ERROR: DgQ2DDtoIConverter::convertTypedAddress():  coordinate out of range: (51, 81)
```

**Comment by AquaAuma** [comment]
@jepa this is the code line where we are getting the issue https://github.com/AquaAuma/FishGlob_data/blob/0cd5dff3a2796e33f4e3b3a506ffb91aec34fbd0/functions/apply_trimming_method1.R#L34

I am thinking it might be an R spatial package problem with versions + a specific problem with GSL-N

**Comment by jepa** [comment]
Weird. I didn't had the error at that level. Mine happens in line 55... 

https://github.com/AquaAuma/FishGlob_data/blob/0cd5dff3a2796e33f4e3b3a506ffb91aec34fbd0/functions/apply_trimming_method1.R#L55C13-L55C13


Also, how do you make it so that I can see the line!?!?!?

**Comment by jepa** [comment]
If I interpret the error correctly, it is saying that there is A) an issue with the the coordinates (latitude 51, longitude 81) or with latitude 51 and 81 on the `unique_latlon` data. I've explored this and I can't seem to find an obvious issue o=with latitude 51 (there is no longitude nor latitude 81). That being said... It has nothing to do with those points in the original map that are not supposed to be there. So I think this is not the actual issue

<img width="621" alt="Screenshot 2023-11-28 at 10 57 49 AM" src="https://github.com/AquaAuma/FishGlob_data/assets/16725517/8e8cd3af-162d-460e-acb9-ce8b752aeed4">

**Comment by jepa** [comment]
Again... these are 6 examples of coordinates that give such error ... 

<img width="622" alt="Screenshot 2023-11-28 at 11 12 16 AM" src="https://github.com/AquaAuma/FishGlob_data/assets/16725517/adad5b5f-2d75-4edc-8f97-235a2d4e8148">

**Comment by AquaAuma** [comment]
Nothing seems wrong with the actual coordinates rights? They're all continuous values

**Comment by AquaAuma** [comment]
yeah, so strange. Do you know if the code is assigning these two grid cells to long lats from the survey data that seem to be in the Pacific? I'm wondering if some long lats have an issue with the function

**Comment by jepa** [comment]
This is how the protocol looks like once fixed. Questions? Thoughts? Concerns? "This-is-morelike-a-commet"? 

<img width="1130" alt="Screenshot 2023-11-28 at 12 09 42 PM" src="https://github.com/AquaAuma/FishGlob_data/assets/16725517/f3f06bf7-6cdd-4420-bc16-b0322544b695">

**Comment by jepa** [comment]
Quick fix is dropping data so no good.

**Comment by jepa** [comment]
Sooooooo... THIS-IS-JUST-GREAT... Turns out the problem with `dggridR::dgGEO_to_SEQNUM()` is related to MAC, specifically to those with M1 or >M1 chips, which is my case (and I am guessing yours too @AquaAuma ). I ran the script in the lab's PC and it worked-just-F-fine... This is the output...

<img width="1181" alt="Screenshot 2023-11-28 at 4 07 35 PM" src="https://github.com/AquaAuma/FishGlob_data/assets/16725517/b97b6b40-a1ea-49e1-aead-d992447aac00">

**Comment by jepa** [comment]
Let me know if this is good and I can commit the changes

**Comment by jepa** [comment]
There is also a fix for MAC users see [here](https://github.com/r-barnes/dggridR/issues/63). Basically, it fixes the issu if you update the `dggridR` package to 3.1.0 using the source code `remotes::install_github("SebKrantz/dggridR")`. I did that and it ran smoothly on my mac. I've gone ahead and pushed [10a0d62](https://github.com/AquaAuma/FishGlob_data/commit/10a0d6234fd01ab25842eec1719fcdf706fb71d8) the updated outputs

**Comment by AquaAuma** [comment]
wow ok, thank you so much!! I'm glad we found what the problem was... feel free to push, it looks right
