### ISSUE TITLE
NA_compile

### ISSUE THREAD

**Issue by AquaAuma** [AquaAuma/FishGlob_data#4]
@zoekitchel @mpinsky any idea if we still need the north_america_compile.R script on GitHub? Does not seem useful to me when looking at individual survey scripts?

**Comment by AquaAuma** [comment]
@mpinsky ? or maybe we can ask Dan, or I'll just delete

**Comment by mpinsky** [comment]
If we don't use it for FISHGLOB, then lets delete it. @AquaAuma
