### ISSUE TITLE
From Ed Lavender on gear types (DFO/US)

### ISSUE THREAD

**Issue by AquaAuma** [AquaAuma/FishGlob_data#9]
"Missing types. Gear type records are missing for some surveys (DFO-HS, DFO-QCS, DFO-SOG, DFO-WCHG, DFO-WCVI and WCANN). Is this intentional? My understanding is that most of these surveys use a Western IIA trawl but I imagine there may be differences in set up. "

@zoekitchel @mpinsky

**Comment by AquaAuma** [comment]
@zoekitchel @mpinsky just to make sure we get this corrected? thank you

**Comment by mpinsky** [comment]
@James-Thorson-NOAA , you probably know the gear types for WCANN?

**Comment by mpinsky** [comment]
Perhaps we leave this blank for now since we don't know.

**Comment by James-Thorson-NOAA** [comment]
Sorry but I'm not sure!  Do you want me to email Sean Anderson at DFO and cc y'all to ask?

**Comment by AquaAuma** [comment]
@James-Thorson-NOAA do you know for WCANN though?
For DFO surveys, we can leave as is, but it'd be great someone can double check the gear was not reported but lost in the code, and I might have re-created a column that pre-existed. If the gear is not consistently reported in the database, I don't think we should infer it in the whole dataset at this point

**Comment by James-Thorson-NOAA** [comment]
I don't know what WCANN means ... I assumed that was Western Canada or something ... or maybe it refers to what we often call the West Coast Groundfish Bottom Trawl Survey (WCGBTS)?

**Comment by James-Thorson-NOAA** [comment]
Sorry that I'm slow on the context here!  Yes, I know that the WCGBTS (WCANN in that table) has used the same gear the entire time.  From context, I gather that we just need to add a code (WCANN) to a separate table in a Gear field?  If this is correct, I agree with that plan.

**Comment by AquaAuma** [comment]
it's that the gear column in the integrated dataset itself for now says <NA>, so we wanted to see if we can replace that, seems like we can! thanks Jim

**Comment by mpinsky** [comment]
@jepa, we can add gear information for WCANN (Four-panel Aberdeen 85/104' bottom-trawl equipped with net mensuration gear; per Aurore's table above). For DFO-HS, DFO-QCS, DFO-SOG, DFO-WCHG, DFO-WCVI, we will leave gear blank.

**Comment by jepa** [comment]
Done. See my last push. Will push after reviewing all.
